# USER CALLS #
@base_URL = http://34.22.159.109:3000/api/users
@userId = 665f4e0f04e74a6982cfa603
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjVmNGUwZjA0ZTc0YTY5ODJjZmE2MDMiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzE3NTIxOTgwLCJleHAiOjE3MTc1MjU1ODB9.KqljPo7oT7JXnJ-_lckAmj89YHe4MLIohrLpkmSgJY8

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjYwOWI0ZmUyM2UxOGYzYzgxODcxM2EiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MTc2MjM0NDIsImV4cCI6MTcxNzYyNzA0Mn0.GhRrWSNl_vdosgSGu_Jgix-sMOVVnHNfr3DkEqviXVE



get {{base_URL}}/{{userId }}
Content-Type: application/json

###

post {{base_URL}}
Content-Type: application/json


# {
#     name: string (required, min 5 characters, max 50 characters),
#     email: string (required, min 5 characters, max 255 characters, valid email format),
#     password: string (required, min 5 characters, max 255 characters)
# }

{
   "name": "Fabian",
   "email": "gebruiker5@gmail.com",
   "password": "password"
}

###

get {{base_URL}}/me
x-auth-token: {{authToken}}


###

get {{base_URL}}/me
x-auth-token: {{adminToken}}
