# MALLS CALLS #

@base_url = http://34.22.159.109:3000/api/malls
@mallId = 66446492597a6b32a34d1f1f
@storeId = 6642fcf9dea6fae5df21f235
@employeeId = 664465dba5e89619af9d45f2
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjVmNGUwZjA0ZTc0YTY5ODJjZmE2MDMiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzE3NTIxOTgwLCJleHAiOjE3MTc1MjU1ODB9.KqljPo7oT7JXnJ-_lckAmj89YHe4MLIohrLpkmSgJY8
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjYwOWI0ZmUyM2UxOGYzYzgxODcxM2EiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MTc2MjM0NDIsImV4cCI6MTcxNzYyNzA0Mn0.GhRrWSNl_vdosgSGu_Jgix-sMOVVnHNfr3DkEqviXVE



get {{base_url}}

###

get {{base_url}}/{{mallId}}


###

get {{base_url}}/{{mallId}}/stores

###

get {{base_url}}/{{mallId}}/employees


###

get {{base_url}}/{{mallId}}/{{employeeId}}


###
post {{base_url}}/
x-auth-token: {{authToken}}
Content-Type: application/json 

# {
#     name: string (required, min 2 characters, max 100 characters),
#     address: string (required, min 10 characters),
#     city: string (required, min 3 characters),
#     province: string (required, min 10 characters) ("West-Vlaanderen", "Oost-Vlaanderen", "Limburg", "Antwerpen", "Vlaams-Brabant", "Luik", "Henegouwen", "Luxemburg", "Namen", "Waals-Brabant")
#     postalCode: string (required, min 4 characters, max 4 characters)
# }

{
    "name": "Frunpark", 
    "address" : "Krekekstraat 58",
    "city": "Izegem",
    "province": "West-Vlaanderen",
    "postalCode": "8870"
}

###

post {{base_url}}/{{mallId}}/{{storeId}}
x-auth-token: {{authToken}}


###

post {{base_url}}/{{mallId}}/{{storeId}}/employees
x-auth-token: {{authToken}}
Content-Type: application/json

# {
#     firstName: string (required, min 5 characters, max 75 characters),
#     lastName: string (required, min 5 characters, max 50 characters),
#     type: string (required, min 5 characters, max 50 characters),
#     salary: number (required),
#     hireDate: date (required)
# }

{
    "firstName": "John",
    "lastName": "Doe",
    "type": "Manager",
    "hireDate": "2015-05-06",
    "salary": 100000
}

### 

put {{base_url}}/{{mallId}}
x-auth-token: {{authToken}}
Content-Type: application/json

# {
#     name: string (required, min 2 characters, max 100 characters),
#     address: string (required, min 10 characters),
#     city: string (required, min 3 characters),
#     province: string (required, min 10 characters) ("West-Vlaanderen", "Oost-Vlaanderen", "Limburg", "Antwerpen", "Vlaams-Brabant", "Luik", "Henegouwen", "Luxemburg", "Namen", "Waals-Brabant")
#     postalCode: string (required, min 4 characters, max 4 characters)
# }

{
    "name": "Frunpark", 
    "address" : "Roeselaarsestraat 757",
    "city": "Izegem",
    "province": "West-vlaanderen",
    "postalCode": "8870"
}


###


put {{base_url}}/{{mallId}}/{{employeeId}}
x-auth-token: {{authToken}}
Content-Type: application/json

# {
#     firstName: string (required, min 5 characters, max 75 characters),
#     lastName: string (required, min 5 characters, max 50 characters),
#     type: string (required, min 5 characters, max 50 characters),
#     salary: number (required),
#     hireDate: date (required)
# }

{
    "firstName": "Fabian",
    "lastName": "Ehis",
    "type": "Intern",
    "hireDate": "2024-05-06",
    "salary": 500
}


###

delete {{base_url}}/{{mallId}}
x-auth-token: {{adminToken}}


###


delete {{base_url}}/{{mallId}}/employee/{{employeeId}}
x-auth-token: {{adminToken}}

